### ISSUE TITLE
Cannot generate the sample - error in spirit-board.ts

### ISSUE THREAD

**Issue by LindsayO94** [LokiMidgard/spirit-island-renderer#4]
**Describe the bug**
Below is the output I got when I tried to run the code after installing using npm.
sir myTestSpirit\Ashes-renews-the-land.json

 ____        _      _ _                        __ _.--..--._ _
/ ___| _ __ (_)_ __(_) |_                   .-' _/   _/\_   \_'-.
\___ \| '_ \| | '__| | __|                 |__ /   _/\__/\_   \__|
 ___) | |_) | | |  | | |_                     |___/\_\__/  \___|
|____/| .__/|_|_|  |_|\__| _                         \__/
|_ _|_|_| | __ _ _ __   __| |                        \__/
 | |/ __| |/ _` | '_ \ / _` |                         \__/
 | |\__ \ | (_| | | | | (_| |                          \__/
|___|___/_|\__,_|_| |_|\__,_|                       ____\__/___
|  _ \ ___ _ __   __| | ___ _ __ ___ _ __     . - '             ' -.
| |_) / _ \ '_ \ / _` |/ _ \ '__/ _ \ '__|   /                      \
|  _ <  __/ | | | (_| |  __/ | |  __/ |~~~~~~~  ~~~~~ ~~~~~  ~~~ ~~~  ~~~~~
|_| \_\___|_| |_|\__,_|\___|_|  \___|_|  ~~~   ~~~~~   ~ ~~   ~~ ~  ~ ~ ~~ ~
Version: 0.2.7

Render Ashes Renews the Land
TypeError: x.choice.map is not a function
    at C:\Users\linds\AppData\Roaming\npm\node_modules\spirit-island-renderer\lib\spirit-board.js:14:164
    at Array.map (<anonymous>)
    at Growth (C:\Users\linds\AppData\Roaming\npm\node_modules\spirit-island-renderer\lib\spirit-board.js:14:81)
    at Object.ToFront (C:\Users\linds\AppData\Roaming\npm\node_modules\spirit-island-renderer\lib\spirit-board.js:130:998)
    at C:\Users\linds\AppData\Roaming\npm\node_modules\spirit-island-renderer\lib\render.js:149:68
    at step (C:\Users\linds\AppData\Roaming\npm\node_modules\spirit-island-renderer\lib\render.js:33:23)
    at Object.next (C:\Users\linds\AppData\Roaming\npm\node_modules\spirit-island-renderer\lib\render.js:14:53)
    at step (C:\Users\linds\AppData\Roaming\npm\node_modules\spirit-island-renderer\lib\render.js:18:139)
    at Object.next (C:\Users\linds\AppData\Roaming\npm\node_modules\spirit-island-renderer\lib\render.js:14:53)
    at fulfilled (C:\Users\linds\AppData\Roaming\npm\node_modules\spirit-island-renderer\lib\render.js:5:58)

**To Reproduce**
I installed node first and it added itself to my PATH. Then I ran "npm i spirit-island-renderer@latest -g".
Then I ran "spirit-island-renderer --generate-sample myTestSpirit" but this didn't work - I had to use "sir" instead as "spirit-island-renderer" wasn't found. Then that command ran fine.
Then I ran "sir myTestSpirit\Ashes-renews-the-land.json" and got the output above.

I'm not sure I have TypeScript installed, but I'm also not sure how to do that correctly. It didn't mention needing to do this in the readme. "tsc -v" does not work.

**Expected behavior**
The out folder to have output, and no errors to occur.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 19041

**Comment by LokiMidgard** [comment]
It's some time since I worked on this...
And I don't know when I find time to debug the source code (Maybe this weekend). But I have some ideas.

You should not need to install TypeScript to use it. Everything needed should be installed by npm.

But one Problem could be that the Sample is not up to date. I may have made changes (something is now an array that was not an array before) without updating the sample.

There is a [repo](https://github.com/LokiMidgard/spirit-island-custom-spirits) that contains two of my custom spirits. And that worked 5 month ago. It also contains the ashes Renews the land spirit, but there are some differences in the json. Can you try if that spirit works?

Does your code editor uses the  json schema to validate the json and give you auto completion? If yes do you have warnings or errors in the sample?
